#pragma once

#include <Arduino.h>
#include <Preferences.h>

/**
 * Runtime configuration held in NVS (Preferences).
 *
 * Why NVS and not compile-time constants (ARCHITECTURE.md §14, prompt §42):
 *   - Wi-Fi credentials change without a reflash
 *   - the device secret is generated by the SERVER and must never be in source
 *   - the sample counter must survive a power loss so `sampleId` stays unique
 *     (a repeated id would be deduplicated away and the data silently lost)
 *
 * Identity (`dev.id`, `dev.secret`) survives a factory reset; only network and
 * presentation keys are wiped.
 */
class NvsConfig {
 public:
  bool begin();

  // ---- Wi-Fi + endpoint (never compiled in) ----
  String wifiSsid() const;
  String wifiPass() const;
  String serverBase() const;
  void setWifi(const String& ssid, const String& pass);
  void setServerBase(const String& base);
  bool hasWifi() const;

  // ---- device identity (written once by provisioning) ----
  String deviceId() const;
  String deviceSecret() const;
  bool hasIdentity() const;
  void setIdentity(const String& deviceId, const String& secret);
  void clearIdentity();

  // ---- idempotency ----
  uint32_t nextSequence();

  // ---- device configuration ----
  uint32_t sampleIntervalS() const;
  void setSampleIntervalS(uint32_t seconds);
  float windCalibrationCoef() const;
  void setWindCalibrationCoef(float coef);

  // ---- CCS811 burn-in accounting (quality flag only, persisted) ----
  uint32_t ccsHours() const;
  void addCcsHour();

  // ---- counters (surfaced in the heartbeat) ----
  void countSent(uint32_t n);
  void countRejected(uint32_t n);
  void countCorrupt(uint32_t n);
  void countDropped(uint32_t n);
  uint32_t sentCount() const;
  uint32_t rejectedCount() const;
  uint32_t corruptCount() const;
  uint32_t droppedCount() const;

  /** Forget Wi-Fi + server (long press). Identity and counters are KEPT. */
  void forgetNetwork();

 private:
  mutable Preferences prefs_;
  bool open_ = false;
};

extern NvsConfig Config;
